library(jsonlite)
library(plyr)

load_taxonomy <- function(file){
  rawdata <- fromJSON(file)
  taxonomy <- flatten_taxonomy(NULL, rawdata[[2]])
  return(taxonomy)
}


flatten_taxonomy <- function(flattened, nested) {

  if(is.list(nested) & length(nested) == 0 ){
    return(flattened)
  }
  
  tmp <- nested
  
  #flatten ID lists
  tmp$children_ids <- unlist(lapply(nested$children_ids, paste0, collapse = ','))
  tmp$full_path_taxonomy_ids <- unlist(lapply(nested$full_path_taxonomy_ids, paste0, collapse = ','))
  tmp$children <- NULL
  tmp$nav <- NULL
  tmp$is_supplies_top_level <- NULL
  
  #remove factors
  tmp[] <- lapply(tmp, as.character)

  if(is.null(flattened)){
    flattened <- tmp
  } else {
    flattened <- rbind(flattened, tmp)
  }
    
  children <- adply(nested$children, c(1), function(x) flatten_taxonomy(NULL, x))
  children$X1 <- NULL #additional column generated by adply
  
  flattened <- rbind(flattened, children)
    
  return(flattened)
  
}