library(jsonlite)
library(plyr)
library(httr)
library(lubridate)

save_taxonomy <- function(etsyAPIkey, filename = ""){

  url <- paste("https://openapi.etsy.com/v2/taxonomy/buyer/get?api_key=", etsyAPIkey, sep = "")
  taxonomy <- GET(url)
  taxonomy_json <- content(taxonomy, as = "text") 

  if(str_length(filename) == 0  ) {
    filename <- paste("taxonomy", format(today(), format="%d%b%Y"), sep = "_")
    filename <- paste(filename, "json", sep=".")
  }
  
  write(taxonomy_json, filename)
  
}

load_taxonomy <- function(file){
  rawdata <- fromJSON(file)
  taxonomy <- flatten_taxonomy(NULL, rawdata[[2]])
  return(taxonomy)
}


flatten_taxonomy <- function(flattened, nested) {

  if(is.list(nested) & length(nested) == 0 ){
    return(flattened)
  }
  
  tmp <- nested
  
  #flatten ID lists
  tmp$children_ids <- unlist(lapply(nested$children_ids, paste0, collapse = ','))
  tmp$full_path_taxonomy_ids <- unlist(lapply(nested$full_path_taxonomy_ids, paste0, collapse = ','))
  tmp$children <- NULL
  tmp$nav <- NULL
  tmp$is_supplies_top_level <- NULL
  
  #remove factors
  tmp[] <- lapply(tmp, as.character)

  if(is.null(flattened)){
    flattened <- tmp
  } else {
    flattened <- rbind(flattened, tmp)
  }
    
  children <- adply(nested$children, c(1), function(x) flatten_taxonomy(NULL, x))
  children$X1 <- NULL #additional column generated by adply
  
  flattened <- rbind(flattened, children)
    
  return(flattened)
  
}